apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - food-api.simon-zengerling.de
      secretName: tls-food-api
  rules:
  - host: food-api.simon-zengerling.de
    http:
      paths:
      - path: /.*
        pathType: Prefix
        backend:
          service:
            name: food-app-backend-svc
            port:
              number: 8080
