apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: food-app
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      imagePullSecrets:
      - name: ghcr
      containers:
      - name: frontend 
        image: ghcr.io/sijoma/food-app/food-app-frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi