apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: food-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:  
  tls:
    - hosts:
        - food.simon-zengerling.de
      secretName: letsencrypt-prod-tls-food
  rules:
  - host: food.simon-zengerling.de
    http:
      paths:
      - path: /.*
        pathType: Prefix
        backend:
          service:
            name: food-app-frontend-svc
            port:
              number: 80
