apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: food-app
data:
  nginx.conf: |
    server { 
    listen 80;
    server_name food.home;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
      }
    }