apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: food-app
data:
  nginx.conf: "server { \n  listen 80;\n\n  location / {\n    root /usr/share/nginx/html;\n
    \   try_files $uri /index.html;\n  }\n}"
