apiVersion: v1
data:
  nginx.status.conf: |
    server {
        listen       8090 default_server;
        location /nginx_status {
            stub_status;
            access_log off;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-status-conf
  namespace: food-app
