apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-svc-monitor
  namespace: food-app
  labels: 
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: metrics
    interval: 30s
