apiVersion: v1
kind: Service
metadata:
  name: food-app-frontend-svc
  namespace: food-app
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
  - port: 9113
    protocol: TCP
    targetPort: 9113
    name: metrics
